<?php
{$tr=array(
'tipoC'=>array('t'=>'TIPO DE COMPROBANTE (OBLIGATORIO)','d'=>'C'),
'codiC'=>array('t'=>'CÓDIGO COMPROBANTE ~(OBLIGATORIO)','d'=>'30'),
'noC'=>array('t'=>'NÚMERO DE DOCUMENTO ~(OBLIGATORIO)','d'=>$___D['docSiigo']),
'accCode'=>array('t'=>'CUENTA CONTABLE ~~(OBLIGATORIO)'),

'debCred'=>array('t'=>'DÉBITO O CRÉDITO (OBLIGATORIO)'),
'valorSec'=>array('t'=>'VALOR DE LA SECUENCIA ~~(OBLIGATORIO)'),
'docYear'=>array('t'=>'AÑO DEL DOCUMENTO'),
'docMonth'=>array('t'=>'MES DEL DOCUMENTO'),
'docDay'=>array('t'=>'DÍA DEL DOCUMENTO'),
'slpId'=>array('t'=>'CÓDIGO DEL VENDEDOR'),
'cityId'=>array('t'=>'CÓDIGO DE LA CIUDAD'),
'zoneId'=>array('t'=>'CÓDIGO DE LA ZONA'),
'lineNum'=>array('t'=>'SECUENCIA'),
'cCosto'=>array('t'=>'CENTRO DE COSTO','d'=>'0'),
'scCosto'=>array('t'=>'SUBCENTRO DE COSTO','d'=>'0'),
'licTradNum'=>array('t'=>'NIT'),
'cardSuc'=>array('t'=>'SUCURSAL'),
'lineText'=>array('t'=>'DESCRIPCIÓN DE LA SECUENCIA'),
'numCheque'=>array('t'=>'NÚMERO DE CHEQUE'),
'compAnulado'=>array('t'=>'COMPROBANTE ANULADO','d'=>'N'),
'codeanulado'=>array('t'=>'CÓDIGO DEL MOTIVO DE DEVOLUCIÓN'),
'pymntGr'=>array('t'=>'FORMA DE PAGO'),
'valSec1'=>array('t'=>'VALOR DEL CARGO 1 DE LA SECUENCIA'),
'valSec2'=>array('t'=>'VALOR DEL CARGO 2 DE LA SECUENCIA'),
'valDesc1'=>array('t'=>'VALOR DEL DESCUENTO 1 DE LA SECUENCIA'),
'valDesc2'=>array('t'=>'VALOR DEL DESCUENTO 2 DE LA SECUENCIA'),
'ivaPorc'=>array('t'=>'PORCENTAJE DEL IVA DE LA SECUENCIA'),
'ivaSec'=>array('t'=>'VALOR DE IVA DE LA SECUENCIA'),
'baseRte'=>array('t'=>'BASE DE RETENCIÓN'),
'baseRteCc'=>array('t'=>'BASE PARA CUENTAS MARCADAS COMO RETEIVA'),
'secGrava'=>array('t'=>'SECUENCIA GRAVADA O EXCENTA','d'=>'N'),
'porAIU'=>array('t'=>'PORCENTAJE AIU'),
'baseAIU'=>array('t'=>'BASE IVA AIU'),
'itemLine'=>array('t'=>'LÍNEA PRODUCTO'),
'itemGr'=>array('t'=>'GRUPO PRODUCTO'),
'itemId'=>array('t'=>'CÓDIGO PRODUCTO'),
'quantity'=>array('t'=>'CANTIDAD'),
'quantity2'=>array('t'=>'CANTIDAD DOS'),
'whsCode'=>array('t'=>'CÓDIGO DE LA BODEGA'),
'ubiCode'=>array('t'=>'CÓDIGO DE LA UBICACIÓN'),
'cantFactor'=>array('t'=>'CANTIDAD DE FACTOR DE CONVERSIÓN'),
'operFactor'=>array('t'=>'OPERADOR DE FACTOR DE CONVERSIÓN'),
'valFactor'=>array('t'=>'VALOR DEL FACTOR DE CONVERSIÓN'),
'pedidoTipo'=>array('t'=>'TIPO DOCUMENTO DE PEDIDO'),
'pedidoCode'=>array('t'=>'CÓDIGO COMPROBANTE DE PEDIDO'),
'pedidoNum'=>array('t'=>'NÚMERO DE COMPROBANTE PEDIDO'),
'pedidoSec'=>array('t'=>'SECUENCIA DE PEDIDO'),
'tipoCruce'=>array('t'=>'TIPO Y COMPROBANTE CRUCE'),
'numCruce'=>array('t'=>'NÚMERO DE DOCUMENTO CRUCE'),
'numVencimiento'=>array('t'=>'NÚMERO DE VENCIMIENTO'),
'dueYear'=>array('t'=>'AÑO VENCIMIENTO DE DOCUMENTO CRUCE'),
'dueMonth'=>array('t'=>'MES VENCIMIENTO DE DOCUMENTO CRUCE'),
'dueDay'=>array('t'=>'DÍA VENCIMIENTO DE DOCUMENTO CRUCE'),
'lineMemo'=>array('t'=>'DESCRIPCIÓN DE COMENTARIOS'),
'_condiPago'=>array('t'=>'08000-CONDICIONES DE PAGO'),
'_observa'=>array('t'=>'08001-OBSERVACIONES'),
'_ordCompra'=>array('t'=>'08002-ORDEN DE COMPRA'),
'_ordPedido'=>array('t'=>'08003-ORDEN DE PEDIDO'),
'_elaborapoPor'=>array('t'=>'08004-ELABORADO POR'),
'_observa2'=>array('t'=>'08005-OBSERVACION'),
'_observa3'=>array('t'=>'08006-OBSERVACION'),
);
}
?>