<?php
Siigo::$Temp['ivtEgr']=json_decode(
json_encode(['tipoC'=>['t'=>'TIPO DE COMPROBANTE (OBLIGATORIO)','d'=>'H'],
 'codiC'=>['t'=>'CÓDIGO COMPROBANTE ~(OBLIGATORIO)','d'=>c::$V['Itf.siigo']['ivtEgr.codiC']],
 'noC'=>['t'=>'NÚMERO DE DOCUMENTO','d'=>'x'],
 'debAcc'=>['t'=>'CUENTA CONTABLE ~~(OBLIGATORIO)','d'=>'14xx'],
 'debCred'=>['t'=>'DÉBITO O CRÉDITO (OBLIGATORIO)','d'=>'C'],
 'valorSec'=>['t'=>'VALOR DE LA SECUENCIA ~~(OBLIGATORIO)','d'=>'0'],
 'year'=>['t'=>'AÑO DEL DOCUMENTO','d'=>''],
 'month'=>['t'=>'MES DEL DOCUMENTO','d'=>''],
 'day'=>['t'=>'DÍA DEL DOCUMENTO','d'=>''],
 'slpCode'=>['t'=>'CÓDIGO DEL VENDEDOR','d'=>'1'],
 'codeCity'=>['t'=>'CÓDIGO DE LA CIUDAD','d'=>'560'],
 'codeZone'=>['t'=>'CÓDIGO DE LA ZONA','d'=>'0'],
 'lineNum'=>['t'=>'SECUENCIA','d'=>'1'],
 'ccosto'=>['t'=>'CENTRO DE COSTO','d'=>'0'],
 'subccost'=>['t'=>'SUBCENTRO DE COSTO','d'=>'0'],
 'nit'=>['t'=>'NIT','d'=>'x'],
 'SUCURSAL'=>['t'=>'SUCURSAL','d'=>'0'],
 'itemName'=>['t'=>'DESCRIPCIÓN DE LA SECUENCIA','d'=>''],
 'noCheq'=>['t'=>'NÚMERO DE CHEQUE','d'=>'0'],
 'compAnulado'=>['t'=>'COMPROBANTE ANULADO','d'=>'N'],
 'codMotDev'=>['t'=>'CÓDIGO DEL MOTIVO DE DEVOLUCIÓN','d'=>'0'],
 'payMethod'=>['t'=>'FORMA DE PAGO','d'=>'0'],
 'valSec1'=>['t'=>'VALOR DEL CARGO 1 DE LA SECUENCIA','d'=>'0'],
 'valSec2'=>['t'=>'VALOR DEL CARGO 2 DE LA SECUENCIA','d'=>'0'],
 'valDescSec1'=>['t'=>'VALOR DEL DESCUENTO 1 DE LA SECUENCIA','d'=>'0'],
 'valDescSec2'=>['t'=>'VALOR DEL DESCUENTO 2 DE LA SECUENCIA','d'=>'0'],
 'valDescSec3'=>['t'=>'VALOR DEL DESCUENTO 3 DE LA SECUENCIA','d'=>'0'],
 'docFE'=>['t'=>'FACTURA ELECTRÓNICA A DEBITAR/ACREDITAR','d'=>' '],
 'docNumFE'=>['t'=>'NÚMERO DE FACTURA ELECTRÓNICA A DEBITAR/ACREDITAR','d'=>'0'],
 'orderPref'=>['t'=>'PREFIJO DE ORDER REFERENCE','d'=>''],
 'orderNum'=>['t'=>'CONSECUTIVO DE ORDER REFERENCE','d'=>''],
 'delivPref'=>['t'=>'PREFIJO ORDEN DE ENTREGA','d'=>''],
 'delivNum'=>['t'=>'NUMERO ORDEN DE ENTREGA','d'=>''],
 'delivYear'=>['t'=>'AÑO FECHA DE ORDEN DE ENTREGA','d'=>'0'],
 'delivMonth'=>['t'=>'MES FECHA DE ORDEN DE ENTREGA','d'=>'0'],
 'delivDay'=>['t'=>'DÍA FECHA DE ORDEN DE ENTREGA','d'=>'0'],
 'ingCard'=>['t'=>'INGRESOS PARA TERCEROS','d'=>''],
 '_itemLine'=>['t'=>'LÍNEA PRODUCTO','d'=>'47'],
 '_itemGr'=>['t'=>'GRUPO PRODUCTO','d'=>'200'],
 'itemIdSiigo'=>['t'=>'CÓDIGO PRODUCTO','d'=>'100003'],
 'quantity'=>['t'=>'CANTIDAD','d'=>'20000000'],
 'quantity2'=>['t'=>'CANTIDAD DOS','d'=>'0'],
 'whsCode'=>['t'=>'CÓDIGO DE LA BODEGA','d'=>'1'],
 'codeUbi'=>['t'=>'CÓDIGO DE LA UBICACIÓN','d'=>'0'],
 'factorQuantity'=>['t'=>'CANTIDAD DE FACTOR DE CONVERSIÓN','d'=>'0'],
 'factorOper'=>['t'=>'OPERADOR DE FACTOR DE CONVERSIÓN','d'=>'0'],
 'factorValue'=>['t'=>'VALOR DEL FACTOR DE CONVERSIÓN','d'=>'0'],
]),1);
?>