<?php
$THs=json_decode(
json_encode([
 'tipoC'=>['t'=>'TIPO DE COMPROBANTE (OBLIGATORIO)','d'=>'xxx'],
 'codiC'=>['t'=>'CÓDIGO COMPROBANTE ~(OBLIGATORIO)','d'=>'#x'],
 'noC'=>['t'=>'NÚMERO DE DOCUMENTO','d'=>'x'],
 'accCode'=>['t'=>'CUENTA CONTABLE ~~(OBLIGATORIO)','d'=>'14xx'],
 'debCre'=>['t'=>'DÉBITO O CRÉDITO (OBLIGATORIO)','d'=>'D/C'],
 'priceLine'=>['t'=>'VALOR DE LA SECUENCIA ~~(OBLIGATORIO)','d'=>0],
 'year'=>['t'=>'AÑO DEL DOCUMENTO','d'=>''],
 'month'=>['t'=>'MES DEL DOCUMENTO','d'=>''],
 'day'=>['t'=>'DÍA DEL DOCUMENTO','d'=>''],

 'slpCode'=>['t'=>'CÓDIGO DEL VENDEDOR','d'=>1],
 'cityCode'=>['t'=>'CÓDIGO DE LA CIUDAD','d'=>0],
 'codeZone'=>['t'=>'CÓDIGO DE LA ZONA','d'=>0],
 'lineNum'=>['t'=>'SECUENCIA','d'=>1],
 'ccosto'=>['t'=>'CENTRO DE COSTO','d'=>0],
 'subccost'=>['t'=>'SUBCENTRO DE COSTO','d'=>0],
 'nit'=>['t'=>'NIT','d'=>'x'],
 'SUCURSAL'=>['t'=>'SUCURSAL','d'=>0],
 'lineText'=>['t'=>'DESCRIPCIÓN DE LA SECUENCIA','d'=>''],

 'noCheq'=>['t'=>'NÚMERO DE CHEQUE','d'=>0],
 'compAnulado'=>['t'=>'COMPROBANTE ANULADO','d'=>'N'],
 'codMotDev'=>['t'=>'CÓDIGO DEL MOTIVO DE DEVOLUCIÓN','d'=>0],
 'payMethod'=>['t'=>'FORMA DE PAGO','d'=>0],
 'valSec1'=>['t'=>'VALOR DEL CARGO 1 DE LA SECUENCIA','d'=>0],
 'valSec2'=>['t'=>'VALOR DEL CARGO 2 DE LA SECUENCIA','d'=>0],
 'valDescSec1'=>['t'=>'VALOR DEL DESCUENTO 1 DE LA SECUENCIA','d'=>0],
 'valDescSec2'=>['t'=>'VALOR DEL DESCUENTO 2 DE LA SECUENCIA','d'=>0],
 'valDescSec3'=>['t'=>'VALOR DEL DESCUENTO 3 DE LA SECUENCIA','d'=>0],

 'docFE'=>['t'=>'FACTURA ELECTRÓNICA A DEBITAR/ACREDITAR','d'=>' '],
 'docNumFE'=>['t'=>'NÚMERO DE FACTURA ELECTRÓNICA A DEBITAR/ACREDITAR','d'=>0],
 'orderPref'=>['t'=>'PREFIJO DE ORDER REFERENCE','d'=>''],
 'orderNum'=>['t'=>'CONSECUTIVO DE ORDER REFERENCE','d'=>''],
 'delivPref'=>['t'=>'PREFIJO ORDEN DE ENTREGA','d'=>''],
 'delivNum'=>['t'=>'NUMERO ORDEN DE ENTREGA','d'=>''],
 'delivYear'=>['t'=>'AÑO FECHA DE ORDEN DE ENTREGA','d'=>0],
 'delivMonth'=>['t'=>'MES FECHA DE ORDEN DE ENTREGA','d'=>0],
 'delivDay'=>['t'=>'DÍA FECHA DE ORDEN DE ENTREGA','d'=>0],
 'ingCard'=>['t'=>'INGRESOS PARA TERCEROS','d'=>''],
 'cufe'=>['t'=>'CUFE','d'=>''],

 'ivaPorc'=>array('t'=>'PORCENTAJE DEL IVA DE LA SECUENCIA'),
 'ivaSec'=>array('t'=>'VALOR DE IVA DE LA SECUENCIA'),
 'baseRte'=>array('t'=>'BASE DE RETENCIÓN'),
 'baseRteCc'=>array('t'=>'BASE PARA CUENTAS MARCADAS COMO RETEIVA'),
 'secGrava'=>array('t'=>'SECUENCIA GRAVADA O EXCENTA','d'=>'N'),
 'porAIU'=>array('t'=>'PORCENTAJE AIU'),
 'baseAIU'=>array('t'=>'BASE IVA AIU'),
 'valImpcos'=>array('t'=>'VALOR TOTAL IMPOCONSUMO DE LA SECUENCIA','d'=>0),

 'itemLine'=>['t'=>'LÍNEA PRODUCTO','d'=>'xxx'],
 'itemGr'=>['t'=>'GRUPO PRODUCTO','d'=>'xxxx'],
 'itemId'=>['t'=>'CÓDIGO PRODUCTO','d'=>'xxxxyy'],
 'quantity'=>['t'=>'CANTIDAD','d'=>0],
 'quantity2'=>['t'=>'CANTIDAD DOS','d'=>0],
 'whsCode'=>['t'=>'CÓDIGO DE LA BODEGA','d'=>'1'],
 'codeUbi'=>['t'=>'CÓDIGO DE LA UBICACIÓN','d'=>0],
 'factorQuantity'=>['t'=>'CANTIDAD DE FACTOR DE CONVERSIÓN','d'=>0],
 'factorOper'=>['t'=>'OPERADOR DE FACTOR DE CONVERSIÓN','d'=>0],
 'factorValue'=>['t'=>'VALOR DEL FACTOR DE CONVERSIÓN','d'=>0],

/*
'ca1'=>['t'=>'NÚMERO DEL DOCUMENTO DEL PROVEEDOR','d'=>''],
'ca1'=>['t'=>'PREFIJO DEL DOCUMENTO DEL PROVEEDOR','d'=>''],,
'ca1'=>['t'=>'AÑO DOCUMENTO DEL PROVEEDOR','d'=>''],
'ca1'=>['t'=>'MES DOCUMENTO DEL PROVEEDOR','d'=>''],
'ca1'=>['t'=>'DÍA DOCUMENTO DEL PROVEEDOR','d'=>''],
'ca1'=>['t'=>'TIPO DOCUMENTO DE PEDIDO','d'=>''],
'ca1'=>['t'=>'CÓDIGO COMPROBANTE DE PEDIDO','d'=>''],
'ca1'=>['t'=>'NÚMERO DE COMPROBANTE PEDIDO','d'=>''],
'ca1'=>['t'=>'SECUENCIA DE PEDIDO','d'=>''],
'ca1'=>['t'=>'CÓDIGO DE LA MONEDA','d'=>''],
'ca1'=>['t'=>'TASA DE CAMBIO','d'=>''],
'ca1'=>['t'=>'VALOR DE LA SECUENCIA EN EXTRANJERA','d'=>''],
'ca1'=>['t'=>'TIPO DE MONEDA ELABORACIÓN','d'=>''],
'ca1'=>['t'=>'TIPO Y COMPROBANTE CRUCE','d'=>''],
'ca1'=>['t'=>'NÚMERO DE DOCUMENTO CRUCE','d'=>''],
'ca1'=>['t'=>'NÚMERO DE VENCIMIENTO','d'=>''],
'ca1'=>['t'=>'AÑO VENCIMIENTO DE DOCUMENTO CRUCE','d'=>''],
'ca1'=>['t'=>'MES VENCIMIENTO DE DOCUMENTO CRUCE','d'=>''],
'ca1'=>['t'=>'DÍA VENCIMIENTO DE DOCUMENTO CRUCE','d'=>''],

'ca1'=>['t'=>'CONCEPTO DE NÓMINA','d'=>''],
'ca1'=>['t'=>'CANTIDAD (DÍAS /HORAS. ETC)','d'=>''],
'ca1'=>['t'=>'TIPO DE PAGO','d'=>''],
'ca1'=>['t'=>'DESCRIPCIÓN DE COMENTARIOS','d'=>''],
'ca1'=>['t'=>'DESCRIPCIÓN LARGA','d'=>''],

'ca1'=>['t'=>'INCONTERM','d'=>''],
'ca1'=>['t'=>'DESCRIPCIÓN EXPORTACIÓN','d'=>''],
'ca1'=>['t'=>'MEDIO DE TRANSPORTE','d'=>''],
'ca1'=>['t'=>'PAÍS DE ORIGEN','d'=>''],
'ca1'=>['t'=>'CIUDAD DE ORIGEN','d'=>''],
'ca1'=>['t'=>'PAIS DESTINO','d'=>''],
'ca1'=>['t'=>'CIUDAD DESTINO','d'=>''],
'ca1'=>['t'=>'PESO NETO','d'=>''],
'ca1'=>['t'=>'PESO BRUTO','d'=>''],
'ca1'=>['t'=>'UNIDAD DE MEDIDA NETO','d'=>''],
'ca1'=>['t'=>'UNIDAD DE MEDIDA BRUTO','d'=>''],
'ca1'=>['t'=>'CONCEPTO FACTURACION EN BLOQUE','d'=>''],
'ca1'=>['t'=>'DATOS ESTABLEC. (L=LOCAL O=OFICINA)','d'=>''],
'ca1'=>['t'=>'NÚMERO ESTABLECIMIENTO','d'=>''],

'ca1'=>['t'=>'08000-NOMBRE SEGUNDO-TITULAR','d'=>''],
'ca1'=>['t'=>'08001-NIT SEGUNDO TITULAR','d'=>''],
'ca1'=>['t'=>'08002-ORDEN DE COMPRA','d'=>''],
'ca1'=>['t'=>'08003-FECHA ORDEN DE COMPRA','d'=>''],
'ca1'=>['t'=>'08004-FORMA DE PAGO','d'=>''],
'ca1'=>['t'=>'08005-INCOTERM','d'=>''],
'ca1'=>['t'=>'08006-DESPACHO VIA','d'=>''],
'ca1'=>['t'=>'08007-REMISION','d'=>''],
'ca1'=>['t'=>'08008-OBSERVACIONES','d'=>''],
'ca1'=>['t'=>'08009-OBSERVACIONES','d'=>''],
'ca1'=>['t'=>'08010-OBSERVACIONES','d'=>''],
'ca1'=>['t'=>'08011-ANTICIPO','d'=>''],
'ca1'=>['t'=>'08012-PESO','d'=>''],
'ca1'=>['t'=>'08013-VOLUMEN','d'=>''],
'ca1'=>['t'=>'08956-ORDEN DE COMPRA CARV','d'=>''],
'ca1'=>['t'=>'08959-REMISION CARV','d'=>''],
'ca1'=>['t'=>'08968-OBSERVACION CARV','d'=>''],
'ca1'=>['t'=>'08014-SEGUNDA DIRECCION DEL TITULAR','d'=>''],
'ca1'=>['t'=>'08969-PEDIDOS_','d'=>''],
*/

]),1);
?>